[package]
name = "add"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[net]
git-fetch-with-cli = true


[dependencies]
wasmtime = "0.30.0"
anyhow = "1.0.44"
